### ISSUE TITLE
Hub Scan Task - Not obtaining "Phase"

### ISSUE THREAD

**Issue by bgeveritt** [blackducksoftware/hub-bamboo#16]
Hard to reproduce, as it seems intermittent, but here's the logs:

> simple  12-Sep-2016 14:55:10   Starting task 'Black Duck Hub Scan Task' of type 'com.blackducksoftware.integration.hub-bamboo:hubScanTask'
> simple  12-Sep-2016 14:55:11   --> Hub Server Url : <NOT SHOWN>
> simple  12-Sep-2016 14:55:11   --> Hub User : sysadmin
> simple  12-Sep-2016 14:55:11   Initializing - Hub Bamboo Plugin
> simple  12-Sep-2016 14:55:11   -> Bamboo home directory: /opt/app/code/automate/agent
> simple  12-Sep-2016 14:55:11   -> Using Url : <NOT SHOWN>
> simple  12-Sep-2016 14:55:11   -> Using Username : sysadmin
> simple  12-Sep-2016 14:55:11   -> Using Build Full Name : CollabOrative Development Ecosystem - meta-app - CODE-29-add-a-project-navigation-dropdown - scan #13 (CODE-META47-SCAN-13)
> simple  12-Sep-2016 14:55:11   -> Using Build Number : 13
> simple  12-Sep-2016 14:55:11   -> Using Build Workspace Path : /opt/app/code/automate/agent/xml-data/build-dir/CODE-META47-SCAN
> simple  12-Sep-2016 14:55:11   -> Using Hub Project Name : meta-app, Version : 3.2.2-SNAPSHOT, Phase : UNKNOWNPHASE, Distribution : INTERNAL
> simple  12-Sep-2016 14:55:11   -> Scanning the following targets  :
> simple  12-Sep-2016 14:55:11   -> /opt/app/code/automate/agent/xml-data/build-dir/CODE-META47-SCAN/target/meta-app-3.2.2-SNAPSHOT
> simple  12-Sep-2016 14:55:11   -> Maximum wait time for the BOM Update : 5 minutes
> simple  12-Sep-2016 14:55:11   Running on machine : <NOT SHOWN>
> simple  12-Sep-2016 14:55:11   Checking Hub CLI installation
> error   12-Sep-2016 14:55:11   Status : 412
> error   12-Sep-2016 14:55:11   Response : {"errorMessage":"Input request parsing error. Allowed values for phase are [PLANNING, DEVELOPMENT, RELEASED, DEPRECATED, ARCHIVED]","arguments":{"allowedValues":"[PLANNING, DEVELOPMENT, RELEASED, DEPRECATED, ARCHIVED]","fieldName":"phase"},"errors":null,"errorCode":"{core.rest.allowed.values.message_conversion}"}
> error   12-Sep-2016 14:55:11   Hub Scan Task error
> error   12-Sep-2016 14:55:11        com.blackducksoftware.integration.hub.bamboo.BDBambooHubPluginException: Problem creating the Version.
> error   12-Sep-2016 14:55:11           at com.blackducksoftware.integration.hub.bamboo.tasks.HubScanTask.createVersion(HubScanTask.java:591)
> error   12-Sep-2016 14:55:11           at com.blackducksoftware.integration.hub.bamboo.tasks.HubScanTask.ensureVersionExists(HubScanTask.java:570)
> error   12-Sep-2016 14:55:11           at com.blackducksoftware.integration.hub.bamboo.tasks.HubScanTask.execute(HubScanTask.java:190)
> error   12-Sep-2016 14:55:11           at com.atlassian.bamboo.task.TaskExecutorImpl.lambda$executeTasks$124(TaskExecutorImpl.java:269)
> error   12-Sep-2016 14:55:11           at com.atlassian.bamboo.task.TaskExecutorImpl.executeTaskWithPrePostActions(TaskExecutorImpl.java:202)
> error   12-Sep-2016 14:55:11           at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks(TaskExecutorImpl.java:269)
> error   12-Sep-2016 14:55:11           at com.atlassian.bamboo.task.TaskExecutorImpl.execute(TaskExecutorImpl.java:108)
> error   12-Sep-2016 14:55:11           at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call(ExecuteBuildTask.java:74)
> error   12-Sep-2016 14:55:11           at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:215)
> error   12-Sep-2016 14:55:11           at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:139)
> error   12-Sep-2016 14:55:11           at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:130)
> error   12-Sep-2016 14:55:11           at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:215)
> error   12-Sep-2016 14:55:11           at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:129)
> error   12-Sep-2016 14:55:11           at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent$1.run(DefaultBuildAgent.java:137)
> error   12-Sep-2016 14:55:11           at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:49)
> error   12-Sep-2016 14:55:11           at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:31)
> error   12-Sep-2016 14:55:11           at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:20)
> error   12-Sep-2016 14:55:11           at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:52)
> error   12-Sep-2016 14:55:11           at java.lang.Thread.run(Thread.java:745)
> error   12-Sep-2016 14:55:11   Caused by: com.blackducksoftware.integration.hub.exception.BDRestException: There was a problem creating this Version for the specified Hub Project. Error Code: 412
> error   12-Sep-2016 14:55:11           at com.blackducksoftware.integration.hub.HubIntRestService.createHubVersion(HubIntRestService.java:522)
> error   12-Sep-2016 14:55:11           at com.blackducksoftware.integration.hub.bamboo.tasks.HubScanTask.createVersion(HubScanTask.java:583)
> error   12-Sep-2016 14:55:11           ... 18 more
> simple  12-Sep-2016 14:55:11   HUB Scan Task result: Error
> simple  12-Sep-2016 14:55:11   Finished task 'Black Duck Hub Scan Task' with result: Error

**Comment by akamen** [comment]
We will look into this for next release, any additional steps for reproducing will be helpful.

**Comment by bgeveritt** [comment]
Steps to reproduce:

1. Run an initial scan successfully with parameters "Phase: In Development" and "Distribution: External"
2. On the build plan, change the Black Duck Hub Scan Task parameters to "Phase: In Planning" and "Distribution: External" **AND** increment the version
4. Click Save (you will notice if you click back on the scan task, it will not have saved the phase and distribution)
3. Run build
4. It should error out, with the initial comment's logs

**Comment by akamen** [comment]
@bgeveritt  slated for 2.0.1, reproduced and will be fixed.

**Comment by jrichardBD** [comment]
Fixed, spelling msitake
