### ISSUE TITLE
Please provide a plugin version that is compatible for bamboo v 6.1.1

### ISSUE THREAD

**Issue by roy-mammen** [blackducksoftware/hub-bamboo#24]
Please provide a plugin version that is compatible for bamboo v 6.1.1

**Comment by akamen** [comment]
Hello @roy-mammen , we plan to deprecate plugin support and replace it with our new and much better offering hub-detect.  Please try that and let me know what you think.

https://github.com/blackducksoftware/hub-detect

**Comment by roy-mammen** [comment]
Ari, I don’t think detect will work for my use case. How do I run detect from a locked down windows machine (a windows host with no internet connection)?

Thanks

**Comment by roy-mammen** [comment]
Hi Roy,

I reached out to our Product Manager and he’d be happy to get on a call and help work through any issues with Detect. He says all of the issues you raised can be circumvented. Do you have some availability this week for the three of us to meet?

Best,
Kevin

From: Mammen, Roy [mailto:Roy.Mammen@citadel.com]
Sent: Tuesday, August 29, 2017 12:27 PM
To: 'blackducksoftware/hub-bamboo' <reply@reply.github.com>; blackducksoftware/hub-bamboo <hub-bamboo@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Kevin Cronan <kcronan@blackducksoftware.com>
Subject: RE: [EXT] Re: [blackducksoftware/hub-bamboo] Please provide a plugin version that is compatible for bamboo v 6.1.1 (#24)

Ari, I don’t think detect will work for my use case. How do I run detect from a locked down windows machine (a windows host with no internet connection)?

Thanks

**Comment by akamen** [comment]
You are in an air-gapped environment, very well.  1.1.0 of Detect should provide you with the functionality, estimated time for release: ~2-3 weeks.
