### ISSUE TITLE
Configuring the log level

### ISSUE THREAD

**Issue by jrichardBD** [blackducksoftware/hub-bamboo#4]
The log level should be configurable. The level should be configurable through an environment variable (HUB_LOG_LEVEL) , and when the Build runs we should only be logging messages of that level and below. Default : INFO
Ex :
WARN chosen :
log ERROR and WARN
DEBUG chosen:
log ERROR, WARN, INFO, and DEBUG

**Comment by psantos1113** [comment]
This was fixed with commit d8324c5dc9e83bfc82f1ba32c71d31460fb29494
The wrong issue number was referenced in the commit
